### PR TITLE
Allow to change mask and hint programmatically

### PR DESCRIPTION
**Pull request by eltos**
- Added method `setMask`
- Added method `setSingleCharHint`
- Take care of changes of the InputType via `setInputType`

Related Issue #4

### CODE REVIEW

**Comment by miladsalimiiii** [comment]
in `setSingleCharHint` , hint repeat in per position for example when our `maxLength` is 6 and we set "milad" to `setSingleCharHint` then we have , milad milad milad milad milad milad , how can we set one milad as hint.
@alphamu , @eltos

**Comment by alphamu** [comment]
It's been a while, so I'll have to review the code and get back to you.
However, fr memory, if you provide a string of characters, the widget
should loop through the characters. In your example if the pin is 7 digits,
it should go miladmi.

Regards

**Comment by miladsalimiiii** [comment]
@alphamu , Thank you for your answer but i am sure about this :"milad milad milad milad milad milad" in my example and i am waiting for your new answer.

**Comment by eltos** [comment]
Check this line [here](https://github.com/alphamu/PinEntryEditText/blob/104f0a6df604d82ba2f34a1976652e8436933c4f/pinentryedittext/src/main/java/com/alimuzaffar/lib/pin/PinEntryEditText.java#L330), it's not looping through the characters but repeating the full word. You could add an index easily thought.

@man4ik implemented this.

**Comment by miladsalimiiii** [comment]
This  `canvas.drawText(mSingleCharHint, middle - hintWidth / 2, mCharBottom[i], mSingleCharPaint)` line ?
Index to what ?
We have this  `mPinEntryEditText.setSingleCharHint("milad")` how can we index it?

@eltos

**Comment by eltos** [comment]
@miladsalimiiii From a developer point of view.

**Pull request merged**
